
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 26 19:05:30 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 26;
  public static final int POW = 48;
  public static final int CHAR = 51;
  public static final int CONST = 5;
  public static final int ASTERIX = 40;
  public static final int SLASH = 41;
  public static final int GREATER = 35;
  public static final int LPAREN = 11;
  public static final int SEMI = 7;
  public static final int CONTINUE = 20;
  public static final int LESS = 37;
  public static final int MINUS = 30;
  public static final int RPAREN = 12;
  public static final int AND = 29;
  public static final int RECORD = 10;
  public static final int OR = 28;
  public static final int BOOL = 52;
  public static final int COMMA = 8;
  public static final int CLASS = 44;
  public static final int PLUS = 39;
  public static final int LESSEQ = 38;
  public static final int IF = 16;
  public static final int THIS = 47;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 27;
  public static final int RETURN = 21;
  public static final int EQUAL = 6;
  public static final int SUPER = 45;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int PERCENT = 42;
  public static final int NUMBER = 49;
  public static final int IDENT = 50;
  public static final int BREAK = 19;
  public static final int VOID = 13;
  public static final int NOTSAME = 34;
  public static final int COLON = 43;
  public static final int SAME = 33;
  public static final int LANGLE = 14;
  public static final int LBRACE = 3;
  public static final int ELSE = 25;
  public static final int ENUM = 46;
  public static final int READ = 22;
  public static final int GOTO = 24;
  public static final int WHILE = 18;
  public static final int RANGLE = 15;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 9;
  public static final int PROG = 2;
  public static final int GREATEREQ = 36;
  public static final int PRINT = 23;
  public static final int DO = 17;
}

